on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 1200  # Adjusted timeout to 1200 minutes
    name: Build and Deploy Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
        # Add the following step to ensure the runner has proper permissions
      - name: Set git config safe directory
        run: sudo git config --global --add safe.directory /home/runner/work/DynamicMaps/DynamicMaps

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          npm install
          npm run build
          
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
          skip_app_build: false

      - name: Post Job Cleanup
        if: always()
        run: echo "Cleaning up after job"
